api_platform:
  title: 'MoneyTalkApi'
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
#    paths: ['%kernel.project_dir%/src/entity', '%kernel.project_dir%/config/packages/api_platform/']
    # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
#    resource_class_directories:
#      - '%kernel.project_dir%/src/Entity'
  formats:
    json:     ['application/json']
    jsonld:   ['application/ld+json']
    jsonhal:  ['application/hal+json']
    jsonapi:  ['application/vnd.api+json']
    xml:      ['application/xml', 'text/xml']
    yaml:     ['application/x-yaml']
    csv:      ['text/csv']
    html:     ['text/html']
